project:
  type: website
  output-dir: docs

website:
  title: "lilianhu168.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Data Viz.qmd
      

format:
  html:
    theme: lux 
    css: bootstrap.min.css
    toc: true

editor: visual

