project:
  type: website
  output-dir: docs

website:
  title: "Lilian Hu"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Visualization"
        menu:
          - text: "College Admissions Analysis"
            href: college_admissions.qmd
          - text: "Registered Nurses Analysis"
            href: Registered_Nurses.qmd
      - text: "Text Analysis"
        menu:
          - text: "Twitter Finance Analysis"
            href: TwitterFinance.qmd
      - text: "Simulation Study"
        menu: 
          - text: "100-door Monty Hall Simulation"
            href: Monty_Hall.qmd
format:
  html:
    theme: lux
    css: bootstrap.min.css

editor: visual
